/*
 * awsecommerceservice_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for AudienceRatingEnum enum
 */
type AudienceRatingEnum int

/**
 * Value collection for AudienceRatingEnum enum
 */
const (
    AudienceRating_G AudienceRatingEnum = 1 + iota
    AudienceRating_PG
    AudienceRating_PG13
    AudienceRating_R
    AudienceRating_NC17
    AudienceRating_NR
    AudienceRating_UNRATED
    AudienceRating_ENUM_6
    AudienceRating_ENUM_12
    AudienceRating_ENUM_16
    AudienceRating_ENUM_18
    AudienceRating_FAMILYVIEWING
)

func (r AudienceRatingEnum) MarshalJSON() ([]byte, error) { 
    s := AudienceRatingEnumToValue(r)
    return json.Marshal(s) 
} 

func (r *AudienceRatingEnum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  AudienceRatingEnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts AudienceRatingEnum to its string representation
 */
func AudienceRatingEnumToValue(audienceRatingEnum AudienceRatingEnum) string {
    switch audienceRatingEnum {
        case AudienceRating_G:
    		return "G"		
        case AudienceRating_PG:
    		return "PG"		
        case AudienceRating_PG13:
    		return "PG13"		
        case AudienceRating_R:
    		return "R"		
        case AudienceRating_NC17:
    		return "NC17"		
        case AudienceRating_NR:
    		return "NR"		
        case AudienceRating_UNRATED:
    		return "Unrated"		
        case AudienceRating_ENUM_6:
    		return "Enum_6"		
        case AudienceRating_ENUM_12:
    		return "Enum_12"		
        case AudienceRating_ENUM_16:
    		return "Enum_16"		
        case AudienceRating_ENUM_18:
    		return "Enum_18"		
        case AudienceRating_FAMILYVIEWING:
    		return "FamilyViewing"		
        default:
        	return "G"
    }
}

/**
 * Converts AudienceRatingEnum Array to its string Array representation
*/
func AudienceRatingEnumArrayToValue(audienceRatingEnum []AudienceRatingEnum) []string {
    convArray := make([]string,len( audienceRatingEnum))
    for i:=0; i<len(audienceRatingEnum);i++ {
        convArray[i] = AudienceRatingEnumToValue(audienceRatingEnum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func AudienceRatingEnumFromValue(value string) AudienceRatingEnum {
    switch value {
        case "G":
            return AudienceRating_G
        case "PG":
            return AudienceRating_PG
        case "PG13":
            return AudienceRating_PG13
        case "R":
            return AudienceRating_R
        case "NC17":
            return AudienceRating_NC17
        case "NR":
            return AudienceRating_NR
        case "Unrated":
            return AudienceRating_UNRATED
        case "Enum_6":
            return AudienceRating_ENUM_6
        case "Enum_12":
            return AudienceRating_ENUM_12
        case "Enum_16":
            return AudienceRating_ENUM_16
        case "Enum_18":
            return AudienceRating_ENUM_18
        case "FamilyViewing":
            return AudienceRating_FAMILYVIEWING
        default:
            return AudienceRating_G
    }
}
