/*
 * awsecommerceservice_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for AvailabilityEnum enum
 */
type AvailabilityEnum int

/**
 * Value collection for AvailabilityEnum enum
 */
const (
    Availability_AVAILABLE AvailabilityEnum = 1 + iota
)

func (r AvailabilityEnum) MarshalJSON() ([]byte, error) { 
    s := AvailabilityEnumToValue(r)
    return json.Marshal(s) 
} 

func (r *AvailabilityEnum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  AvailabilityEnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts AvailabilityEnum to its string representation
 */
func AvailabilityEnumToValue(availabilityEnum AvailabilityEnum) string {
    switch availabilityEnum {
        case Availability_AVAILABLE:
    		return "Available"		
        default:
        	return "Available"
    }
}

/**
 * Converts AvailabilityEnum Array to its string Array representation
*/
func AvailabilityEnumArrayToValue(availabilityEnum []AvailabilityEnum) []string {
    convArray := make([]string,len( availabilityEnum))
    for i:=0; i<len(availabilityEnum);i++ {
        convArray[i] = AvailabilityEnumToValue(availabilityEnum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func AvailabilityEnumFromValue(value string) AvailabilityEnum {
    switch value {
        case "Available":
            return Availability_AVAILABLE
        default:
            return Availability_AVAILABLE
    }
}
