/*
 * awsecommerceservice_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for RelationshipEnum enum
 */
type RelationshipEnum int

/**
 * Value collection for RelationshipEnum enum
 */
const (
    Relationship_PARENTS RelationshipEnum = 1 + iota
    Relationship_CHILDREN
)

func (r RelationshipEnum) MarshalJSON() ([]byte, error) { 
    s := RelationshipEnumToValue(r)
    return json.Marshal(s) 
} 

func (r *RelationshipEnum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  RelationshipEnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts RelationshipEnum to its string representation
 */
func RelationshipEnumToValue(relationshipEnum RelationshipEnum) string {
    switch relationshipEnum {
        case Relationship_PARENTS:
    		return "Parents"		
        case Relationship_CHILDREN:
    		return "Children"		
        default:
        	return "Parents"
    }
}

/**
 * Converts RelationshipEnum Array to its string Array representation
*/
func RelationshipEnumArrayToValue(relationshipEnum []RelationshipEnum) []string {
    convArray := make([]string,len( relationshipEnum))
    for i:=0; i<len(relationshipEnum);i++ {
        convArray[i] = RelationshipEnumToValue(relationshipEnum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func RelationshipEnumFromValue(value string) RelationshipEnum {
    switch value {
        case "Parents":
            return Relationship_PARENTS
        case "Children":
            return Relationship_CHILDREN
        default:
            return Relationship_PARENTS
    }
}
