/*
 * awsecommerceservice_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for SimilarityTypeEnum enum
 */
type SimilarityTypeEnum int

/**
 * Value collection for SimilarityTypeEnum enum
 */
const (
    SimilarityType_INTERSECTION SimilarityTypeEnum = 1 + iota
    SimilarityType_RANDOM
)

func (r SimilarityTypeEnum) MarshalJSON() ([]byte, error) { 
    s := SimilarityTypeEnumToValue(r)
    return json.Marshal(s) 
} 

func (r *SimilarityTypeEnum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  SimilarityTypeEnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts SimilarityTypeEnum to its string representation
 */
func SimilarityTypeEnumToValue(similarityTypeEnum SimilarityTypeEnum) string {
    switch similarityTypeEnum {
        case SimilarityType_INTERSECTION:
    		return "Intersection"		
        case SimilarityType_RANDOM:
    		return "Random"		
        default:
        	return "Intersection"
    }
}

/**
 * Converts SimilarityTypeEnum Array to its string Array representation
*/
func SimilarityTypeEnumArrayToValue(similarityTypeEnum []SimilarityTypeEnum) []string {
    convArray := make([]string,len( similarityTypeEnum))
    for i:=0; i<len(similarityTypeEnum);i++ {
        convArray[i] = SimilarityTypeEnumToValue(similarityTypeEnum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func SimilarityTypeEnumFromValue(value string) SimilarityTypeEnum {
    switch value {
        case "Intersection":
            return SimilarityType_INTERSECTION
        case "Random":
            return SimilarityType_RANDOM
        default:
            return SimilarityType_INTERSECTION
    }
}
