/*
 * awsecommerceservice_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package awsecommerceservice_lib

/** The base Uri for API calls */
const BASEURI string = "https://webservices.amazon.com/onca/soap?Service=AWSECommerceService"

