/*
 * awsecommerceservice_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package awsecommerceservicebinding_pkg

import "awsecommerceservice_lib/models_pkg"

/*
 * Interface for the AWSECOMMERCESERVICEBINDING_IMPL
 */
type AWSECOMMERCESERVICEBINDING interface {
    CreateItemSearch (*models_pkg.ItemSearchRequestMsg) (*models_pkg.ItemSearchResponseMsg, error)

    CreateItemLookup (*models_pkg.ItemLookupRequestMsg) (*models_pkg.ItemLookupResponseMsg, error)

    CreateBrowseNodeLookup (*models_pkg.BrowseNodeLookupRequestMsg) (*models_pkg.BrowseNodeLookupResponseMsg, error)

    CreateSimilarityLookup (*models_pkg.SimilarityLookupRequestMsg) (*models_pkg.SimilarityLookupResponseMsg, error)

    CreateCartGet (*models_pkg.CartGetRequestMsg) (*models_pkg.CartGetResponseMsg, error)

    CreateCartAdd (*models_pkg.CartAddRequestMsg) (*models_pkg.CartAddResponseMsg, error)

    CreateCartCreate (*models_pkg.CartCreateRequestMsg) (*models_pkg.CartCreateResponseMsg, error)

    CreateCartModify (*models_pkg.CartModifyRequestMsg) (*models_pkg.CartModifyResponseMsg, error)

    CreateCartClear (*models_pkg.CartClearRequestMsg) (*models_pkg.CartClearResponseMsg, error)

    CreateItemSearch9 (*models_pkg.ItemSearchRequestMsg) (*models_pkg.ItemSearchResponseMsg, error)

    CreateItemLookup10 (*models_pkg.ItemLookupRequestMsg) (*models_pkg.ItemLookupResponseMsg, error)

    CreateBrowseNodeLookup11 (*models_pkg.BrowseNodeLookupRequestMsg) (*models_pkg.BrowseNodeLookupResponseMsg, error)

    CreateSimilarityLookup12 (*models_pkg.SimilarityLookupRequestMsg) (*models_pkg.SimilarityLookupResponseMsg, error)

    CreateCartGet13 (*models_pkg.CartGetRequestMsg) (*models_pkg.CartGetResponseMsg, error)

    CreateCartAdd14 (*models_pkg.CartAddRequestMsg) (*models_pkg.CartAddResponseMsg, error)

    CreateCartCreate15 (*models_pkg.CartCreateRequestMsg) (*models_pkg.CartCreateResponseMsg, error)

    CreateCartModify16 (*models_pkg.CartModifyRequestMsg) (*models_pkg.CartModifyResponseMsg, error)

    CreateCartClear17 (*models_pkg.CartClearRequestMsg) (*models_pkg.CartClearResponseMsg, error)

    CreateItemSearch18 (*models_pkg.ItemSearchRequestMsg) (*models_pkg.ItemSearchResponseMsg, error)

    CreateItemLookup19 (*models_pkg.ItemLookupRequestMsg) (*models_pkg.ItemLookupResponseMsg, error)

    CreateBrowseNodeLookup20 (*models_pkg.BrowseNodeLookupRequestMsg) (*models_pkg.BrowseNodeLookupResponseMsg, error)

    CreateSimilarityLookup21 (*models_pkg.SimilarityLookupRequestMsg) (*models_pkg.SimilarityLookupResponseMsg, error)

    CreateCartGet22 (*models_pkg.CartGetRequestMsg) (*models_pkg.CartGetResponseMsg, error)

    CreateCartAdd23 (*models_pkg.CartAddRequestMsg) (*models_pkg.CartAddResponseMsg, error)

    CreateCartCreate24 (*models_pkg.CartCreateRequestMsg) (*models_pkg.CartCreateResponseMsg, error)

    CreateCartModify25 (*models_pkg.CartModifyRequestMsg) (*models_pkg.CartModifyResponseMsg, error)

    CreateCartClear26 (*models_pkg.CartClearRequestMsg) (*models_pkg.CartClearResponseMsg, error)

    CreateItemSearch27 (*models_pkg.ItemSearchRequestMsg) (*models_pkg.ItemSearchResponseMsg, error)

    CreateItemLookup28 (*models_pkg.ItemLookupRequestMsg) (*models_pkg.ItemLookupResponseMsg, error)

    CreateBrowseNodeLookup29 (*models_pkg.BrowseNodeLookupRequestMsg) (*models_pkg.BrowseNodeLookupResponseMsg, error)

    CreateSimilarityLookup30 (*models_pkg.SimilarityLookupRequestMsg) (*models_pkg.SimilarityLookupResponseMsg, error)

    CreateCartGet31 (*models_pkg.CartGetRequestMsg) (*models_pkg.CartGetResponseMsg, error)

    CreateCartAdd32 (*models_pkg.CartAddRequestMsg) (*models_pkg.CartAddResponseMsg, error)

    CreateCartCreate33 (*models_pkg.CartCreateRequestMsg) (*models_pkg.CartCreateResponseMsg, error)

    CreateCartModify34 (*models_pkg.CartModifyRequestMsg) (*models_pkg.CartModifyResponseMsg, error)

    CreateCartClear35 (*models_pkg.CartClearRequestMsg) (*models_pkg.CartClearResponseMsg, error)

    CreateItemSearch36 (*models_pkg.ItemSearchRequestMsg) (*models_pkg.ItemSearchResponseMsg, error)

    CreateItemLookup37 (*models_pkg.ItemLookupRequestMsg) (*models_pkg.ItemLookupResponseMsg, error)

    CreateBrowseNodeLookup38 (*models_pkg.BrowseNodeLookupRequestMsg) (*models_pkg.BrowseNodeLookupResponseMsg, error)

    CreateSimilarityLookup39 (*models_pkg.SimilarityLookupRequestMsg) (*models_pkg.SimilarityLookupResponseMsg, error)

    CreateCartGet40 (*models_pkg.CartGetRequestMsg) (*models_pkg.CartGetResponseMsg, error)

    CreateCartAdd41 (*models_pkg.CartAddRequestMsg) (*models_pkg.CartAddResponseMsg, error)

    CreateCartCreate42 (*models_pkg.CartCreateRequestMsg) (*models_pkg.CartCreateResponseMsg, error)

    CreateCartModify43 (*models_pkg.CartModifyRequestMsg) (*models_pkg.CartModifyResponseMsg, error)

    CreateCartClear44 (*models_pkg.CartClearRequestMsg) (*models_pkg.CartClearResponseMsg, error)

    CreateItemSearch45 (*models_pkg.ItemSearchRequestMsg) (*models_pkg.ItemSearchResponseMsg, error)

    CreateItemLookup46 (*models_pkg.ItemLookupRequestMsg) (*models_pkg.ItemLookupResponseMsg, error)

    CreateBrowseNodeLookup47 (*models_pkg.BrowseNodeLookupRequestMsg) (*models_pkg.BrowseNodeLookupResponseMsg, error)

    CreateSimilarityLookup48 (*models_pkg.SimilarityLookupRequestMsg) (*models_pkg.SimilarityLookupResponseMsg, error)

    CreateCartGet49 (*models_pkg.CartGetRequestMsg) (*models_pkg.CartGetResponseMsg, error)

    CreateCartAdd50 (*models_pkg.CartAddRequestMsg) (*models_pkg.CartAddResponseMsg, error)

    CreateCartCreate51 (*models_pkg.CartCreateRequestMsg) (*models_pkg.CartCreateResponseMsg, error)

    CreateCartModify52 (*models_pkg.CartModifyRequestMsg) (*models_pkg.CartModifyResponseMsg, error)

    CreateCartClear53 (*models_pkg.CartClearRequestMsg) (*models_pkg.CartClearResponseMsg, error)

    CreateItemSearch54 (*models_pkg.ItemSearchRequestMsg) (*models_pkg.ItemSearchResponseMsg, error)

    CreateItemLookup55 (*models_pkg.ItemLookupRequestMsg) (*models_pkg.ItemLookupResponseMsg, error)

    CreateBrowseNodeLookup56 (*models_pkg.BrowseNodeLookupRequestMsg) (*models_pkg.BrowseNodeLookupResponseMsg, error)

    CreateSimilarityLookup57 (*models_pkg.SimilarityLookupRequestMsg) (*models_pkg.SimilarityLookupResponseMsg, error)

    CreateCartGet58 (*models_pkg.CartGetRequestMsg) (*models_pkg.CartGetResponseMsg, error)

    CreateCartAdd59 (*models_pkg.CartAddRequestMsg) (*models_pkg.CartAddResponseMsg, error)

    CreateCartCreate60 (*models_pkg.CartCreateRequestMsg) (*models_pkg.CartCreateResponseMsg, error)

    CreateCartModify61 (*models_pkg.CartModifyRequestMsg) (*models_pkg.CartModifyResponseMsg, error)

    CreateCartClear62 (*models_pkg.CartClearRequestMsg) (*models_pkg.CartClearResponseMsg, error)

    CreateItemSearch63 (*models_pkg.ItemSearchRequestMsg) (*models_pkg.ItemSearchResponseMsg, error)

    CreateItemLookup64 (*models_pkg.ItemLookupRequestMsg) (*models_pkg.ItemLookupResponseMsg, error)

    CreateBrowseNodeLookup65 (*models_pkg.BrowseNodeLookupRequestMsg) (*models_pkg.BrowseNodeLookupResponseMsg, error)

    CreateSimilarityLookup66 (*models_pkg.SimilarityLookupRequestMsg) (*models_pkg.SimilarityLookupResponseMsg, error)

    CreateCartGet67 (*models_pkg.CartGetRequestMsg) (*models_pkg.CartGetResponseMsg, error)

    CreateCartAdd68 (*models_pkg.CartAddRequestMsg) (*models_pkg.CartAddResponseMsg, error)

    CreateCartCreate69 (*models_pkg.CartCreateRequestMsg) (*models_pkg.CartCreateResponseMsg, error)

    CreateCartModify70 (*models_pkg.CartModifyRequestMsg) (*models_pkg.CartModifyResponseMsg, error)

    CreateCartClear71 (*models_pkg.CartClearRequestMsg) (*models_pkg.CartClearResponseMsg, error)

    CreateItemSearch72 (*models_pkg.ItemSearchRequestMsg) (*models_pkg.ItemSearchResponseMsg, error)

    CreateItemLookup73 (*models_pkg.ItemLookupRequestMsg) (*models_pkg.ItemLookupResponseMsg, error)

    CreateBrowseNodeLookup74 (*models_pkg.BrowseNodeLookupRequestMsg) (*models_pkg.BrowseNodeLookupResponseMsg, error)

    CreateSimilarityLookup75 (*models_pkg.SimilarityLookupRequestMsg) (*models_pkg.SimilarityLookupResponseMsg, error)

    CreateCartGet76 (*models_pkg.CartGetRequestMsg) (*models_pkg.CartGetResponseMsg, error)

    CreateCartAdd77 (*models_pkg.CartAddRequestMsg) (*models_pkg.CartAddResponseMsg, error)

    CreateCartCreate78 (*models_pkg.CartCreateRequestMsg) (*models_pkg.CartCreateResponseMsg, error)

    CreateCartModify79 (*models_pkg.CartModifyRequestMsg) (*models_pkg.CartModifyResponseMsg, error)

    CreateCartClear80 (*models_pkg.CartClearRequestMsg) (*models_pkg.CartClearResponseMsg, error)

    CreateItemSearch81 (*models_pkg.ItemSearchRequestMsg) (*models_pkg.ItemSearchResponseMsg, error)

    CreateItemLookup82 (*models_pkg.ItemLookupRequestMsg) (*models_pkg.ItemLookupResponseMsg, error)

    CreateBrowseNodeLookup83 (*models_pkg.BrowseNodeLookupRequestMsg) (*models_pkg.BrowseNodeLookupResponseMsg, error)

    CreateSimilarityLookup84 (*models_pkg.SimilarityLookupRequestMsg) (*models_pkg.SimilarityLookupResponseMsg, error)

    CreateCartGet85 (*models_pkg.CartGetRequestMsg) (*models_pkg.CartGetResponseMsg, error)

    CreateCartAdd86 (*models_pkg.CartAddRequestMsg) (*models_pkg.CartAddResponseMsg, error)

    CreateCartCreate87 (*models_pkg.CartCreateRequestMsg) (*models_pkg.CartCreateResponseMsg, error)

    CreateCartModify88 (*models_pkg.CartModifyRequestMsg) (*models_pkg.CartModifyResponseMsg, error)

    CreateCartClear89 (*models_pkg.CartClearRequestMsg) (*models_pkg.CartClearResponseMsg, error)

    CreateItemSearch90 (*models_pkg.ItemSearchRequestMsg) (*models_pkg.ItemSearchResponseMsg, error)

    CreateItemLookup91 (*models_pkg.ItemLookupRequestMsg) (*models_pkg.ItemLookupResponseMsg, error)

    CreateBrowseNodeLookup92 (*models_pkg.BrowseNodeLookupRequestMsg) (*models_pkg.BrowseNodeLookupResponseMsg, error)

    CreateSimilarityLookup93 (*models_pkg.SimilarityLookupRequestMsg) (*models_pkg.SimilarityLookupResponseMsg, error)

    CreateCartGet94 (*models_pkg.CartGetRequestMsg) (*models_pkg.CartGetResponseMsg, error)

    CreateCartAdd95 (*models_pkg.CartAddRequestMsg) (*models_pkg.CartAddResponseMsg, error)

    CreateCartCreate96 (*models_pkg.CartCreateRequestMsg) (*models_pkg.CartCreateResponseMsg, error)

    CreateCartModify97 (*models_pkg.CartModifyRequestMsg) (*models_pkg.CartModifyResponseMsg, error)

    CreateCartClear98 (*models_pkg.CartClearRequestMsg) (*models_pkg.CartClearResponseMsg, error)
}

/*
 * Factory for the AWSECOMMERCESERVICEBINDING interaface returning AWSECOMMERCESERVICEBINDING_IMPL
 */
func NewAWSECOMMERCESERVICEBINDING() AWSECOMMERCESERVICEBINDING {
    return &AWSECOMMERCESERVICEBINDING_IMPL{}
}