/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CartItem 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5351876148772049989L;
    private String cartItemId;
    private String quantity;
    private String aSIN;
    private String sellerNickname;
    private String title;
    private String productGroup;
    private MetaData164 metaData;
    private Price price;
    private Price itemTotal;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("CartItemId")
    public String getCartItemId ( ) { 
        return this.cartItemId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("CartItemId")
    public void setCartItemId (String value) { 
        this.cartItemId = value;
        notifyObservers(this.cartItemId);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Quantity")
    public String getQuantity ( ) { 
        return this.quantity;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Quantity")
    public void setQuantity (String value) { 
        this.quantity = value;
        notifyObservers(this.quantity);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ASIN")
    public String getASIN ( ) { 
        return this.aSIN;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ASIN")
    public void setASIN (String value) { 
        this.aSIN = value;
        notifyObservers(this.aSIN);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("SellerNickname")
    public String getSellerNickname ( ) { 
        return this.sellerNickname;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("SellerNickname")
    public void setSellerNickname (String value) { 
        this.sellerNickname = value;
        notifyObservers(this.sellerNickname);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Title")
    public String getTitle ( ) { 
        return this.title;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Title")
    public void setTitle (String value) { 
        this.title = value;
        notifyObservers(this.title);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ProductGroup")
    public String getProductGroup ( ) { 
        return this.productGroup;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ProductGroup")
    public void setProductGroup (String value) { 
        this.productGroup = value;
        notifyObservers(this.productGroup);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("MetaData")
    public MetaData164 getMetaData ( ) { 
        return this.metaData;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("MetaData")
    public void setMetaData (MetaData164 value) { 
        this.metaData = value;
        notifyObservers(this.metaData);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Price")
    public Price getPrice ( ) { 
        return this.price;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Price")
    public void setPrice (Price value) { 
        this.price = value;
        notifyObservers(this.price);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ItemTotal")
    public Price getItemTotal ( ) { 
        return this.itemTotal;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ItemTotal")
    public void setItemTotal (Price value) { 
        this.itemTotal = value;
        notifyObservers(this.itemTotal);
    }
 
}
 