/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Cart 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4942145331316223260L;
    private String cartId;
    private String hMAC;
    private String uRLEncodedHMAC;
    private Request162 request;
    private String purchaseURL;
    private String mobileCartURL;
    private Price subTotal;
    private CartItems cartItems;
    private SavedForLaterItems savedForLaterItems;
    private SimilarProducts similarProducts;
    private TopSellers topSellers;
    private NewReleases newReleases;
    private SimilarViewedProducts similarViewedProducts;
    private OtherCategoriesSimilarProducts otherCategoriesSimilarProducts;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("CartId")
    public String getCartId ( ) { 
        return this.cartId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("CartId")
    public void setCartId (String value) { 
        this.cartId = value;
        notifyObservers(this.cartId);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("HMAC")
    public String getHMAC ( ) { 
        return this.hMAC;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("HMAC")
    public void setHMAC (String value) { 
        this.hMAC = value;
        notifyObservers(this.hMAC);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("URLEncodedHMAC")
    public String getURLEncodedHMAC ( ) { 
        return this.uRLEncodedHMAC;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("URLEncodedHMAC")
    public void setURLEncodedHMAC (String value) { 
        this.uRLEncodedHMAC = value;
        notifyObservers(this.uRLEncodedHMAC);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Request")
    public Request162 getRequest ( ) { 
        return this.request;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Request")
    public void setRequest (Request162 value) { 
        this.request = value;
        notifyObservers(this.request);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("PurchaseURL")
    public String getPurchaseURL ( ) { 
        return this.purchaseURL;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("PurchaseURL")
    public void setPurchaseURL (String value) { 
        this.purchaseURL = value;
        notifyObservers(this.purchaseURL);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("MobileCartURL")
    public String getMobileCartURL ( ) { 
        return this.mobileCartURL;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("MobileCartURL")
    public void setMobileCartURL (String value) { 
        this.mobileCartURL = value;
        notifyObservers(this.mobileCartURL);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("SubTotal")
    public Price getSubTotal ( ) { 
        return this.subTotal;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("SubTotal")
    public void setSubTotal (Price value) { 
        this.subTotal = value;
        notifyObservers(this.subTotal);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("CartItems")
    public CartItems getCartItems ( ) { 
        return this.cartItems;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("CartItems")
    public void setCartItems (CartItems value) { 
        this.cartItems = value;
        notifyObservers(this.cartItems);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("SavedForLaterItems")
    public SavedForLaterItems getSavedForLaterItems ( ) { 
        return this.savedForLaterItems;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("SavedForLaterItems")
    public void setSavedForLaterItems (SavedForLaterItems value) { 
        this.savedForLaterItems = value;
        notifyObservers(this.savedForLaterItems);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("SimilarProducts")
    public SimilarProducts getSimilarProducts ( ) { 
        return this.similarProducts;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("SimilarProducts")
    public void setSimilarProducts (SimilarProducts value) { 
        this.similarProducts = value;
        notifyObservers(this.similarProducts);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("TopSellers")
    public TopSellers getTopSellers ( ) { 
        return this.topSellers;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("TopSellers")
    public void setTopSellers (TopSellers value) { 
        this.topSellers = value;
        notifyObservers(this.topSellers);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("NewReleases")
    public NewReleases getNewReleases ( ) { 
        return this.newReleases;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("NewReleases")
    public void setNewReleases (NewReleases value) { 
        this.newReleases = value;
        notifyObservers(this.newReleases);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("SimilarViewedProducts")
    public SimilarViewedProducts getSimilarViewedProducts ( ) { 
        return this.similarViewedProducts;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("SimilarViewedProducts")
    public void setSimilarViewedProducts (SimilarViewedProducts value) { 
        this.similarViewedProducts = value;
        notifyObservers(this.similarViewedProducts);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("OtherCategoriesSimilarProducts")
    public OtherCategoriesSimilarProducts getOtherCategoriesSimilarProducts ( ) { 
        return this.otherCategoriesSimilarProducts;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("OtherCategoriesSimilarProducts")
    public void setOtherCategoriesSimilarProducts (OtherCategoriesSimilarProducts value) { 
        this.otherCategoriesSimilarProducts = value;
        notifyObservers(this.otherCategoriesSimilarProducts);
    }
 
}
 