/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class HTTPHeaders 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4707092303405084778L;
    private List<Header> header;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Header")
    public List<Header> getHeader ( ) { 
        return this.header;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Header")
    public void setHeader (List<Header> value) { 
        this.header = value;
        notifyObservers(this.header);
    }
 
}
 