/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Language 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5009193940694364892L;
    private String name;
    private String type;
    private String audioFormat;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Name")
    public void setName (String value) { 
        this.name = value;
        notifyObservers(this.name);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Type")
    public void setType (String value) { 
        this.type = value;
        notifyObservers(this.type);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("AudioFormat")
    public String getAudioFormat ( ) { 
        return this.audioFormat;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("AudioFormat")
    public void setAudioFormat (String value) { 
        this.audioFormat = value;
        notifyObservers(this.audioFormat);
    }
 
}
 