/*
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.amazon.webservices.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class MCollection 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4929164300897183558L;
    private CollectionSummary collectionSummary;
    private CollectionParent collectionParent;
    private List<CollectionItem> collectionItem;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("CollectionSummary")
    public CollectionSummary getCollectionSummary ( ) { 
        return this.collectionSummary;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("CollectionSummary")
    public void setCollectionSummary (CollectionSummary value) { 
        this.collectionSummary = value;
        notifyObservers(this.collectionSummary);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("CollectionParent")
    public CollectionParent getCollectionParent ( ) { 
        return this.collectionParent;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("CollectionParent")
    public void setCollectionParent (CollectionParent value) { 
        this.collectionParent = value;
        notifyObservers(this.collectionParent);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("CollectionItem")
    public List<CollectionItem> getCollectionItem ( ) { 
        return this.collectionItem;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("CollectionItem")
    public void setCollectionItem (List<CollectionItem> value) { 
        this.collectionItem = value;
        notifyObservers(this.collectionItem);
    }
 
}
 